physics: 
  parabolic_trajectory: 
    x0: 0.0
    y0: 0.0
    v0: 15.0
    angle: 45.0
    g: 9.81
    dt: 0.001
  parabolic_trajectory_multi: 
    x0: 0.0
    y0: 0.0
    v0: 15.0
    angle: 35.0
    g: 9.81
    dt: 0.001
  MRU: 
    x0: 0.0
    y0: 0.0
    v0: 15.0
    angle: 45.0
    dt: 0.001
    t_max: 4
  olita: 
    x0: 0.0
    y0: 0.0
    omega1: 9
    alpha: 2.356194490192345
    omega2: 3
    dt: 0.001
    t_max: 4
  kokoro: 
    x0: 0.0
    y0: 0.0
    dt: 0.001
    t_max: 6
  kokoro_multi: 
    x0: 0.0
    y0: 0.0
    dt: 0.001
    r: 1
    t_max: 6
  MCU_multi:
    x0: 0
    y0: 0
    r: 0.1
    omega: 1
    dt: 0.001
    t_max: 7
  parabolic_trajectory_multi_kokoro:
    x0: 0.0
    y0: 0.0
    v0: 8.0
    angle: 35.0
    g: 9.81
    dt: 0.001